export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const FILTER_ARTICLE_BY_DATA = 'FILTER_ARTICLE_BY_DATA';
export const SET_DATE = 'SET_DATE';
export const ADD_COMMENT = 'ADD_COMMENT';
